<?php

/**
 * @file
 * This file contains page of  Cars, where you can add new entities.
 */

/*
 * Implements hook_entity_info().
 */
function car_module_entity_info() {
    return [
        'car_module' => [
            'label' => t('Car'),
            'base table' => 'cars',
            'entity keys' => [
                'id' => 'cid',
            ],
            'module' => 'car_module',
        ],
    ];
}
/*
 * Implements hook_menu().
 */
function car_module_menu () {
    $items = [];
    $items['cars'] = [
        'title' => 'Cars Page',
        'page callback' => 'drupal_get_form',
        'menu_name' => 'main-menu',
        'page arguments' => ['car_module_form'],
        'access callback' => TRUE,
    ];

    $items['cars/table'] = [
        'title' => 'Database',
        'page callback' => 'table_show_callback',
        'access callback' => TRUE,
    ];

    return $items;
}
/*
 * Implements hook_form().
 */
function car_module_form ($form, &$formstate) {
    $form['markup']['#markup'] = format_string(
        '<h2>@markup</h2>',
        ['@markup' => t('You can add a new car or delete existing')]
    );

    $form['add'] = [
        '#type' => 'submit',
        '#value' => t('Generate'),
        '#submit' => ['car_module_form_add_submit'],
    ];

    $form['show'] = [
        '#type' => 'submit',
        '#value' => t('Show Table'),
        '#submit' => ['car_module_form_show_submit'],
    ];

    $form['delete'] = [
        '#type' => 'submit',
        '#value' => t('Delete'),
        '#submit' => ['car_module_form_delete_submit']
    ];

    return $form;

}
/*
 * Button to generate new cars
 */
function car_module_form_add_submit ($form, &$formstate) {

    $query = db_insert('cars')
        ->fields([
        'name',
        'power',
        'year',
        'price',
    ]);
    $CAR_NAME = [
        'Volkswagen T-Roc',
        'Jaguar E-Pac',
        'BMW X2',
        'Ford EcoSpor',
        'Volvo XC40',
        'Hyundai i30 Tourer',
        'Subaru Impreza',
        'BMW X7',
        'Jeep Wrangler',
        'Dacia Duster',
        'Peugeot 508',
        'Volvo V60',
        'Toyota Auris',
        ];
    for ($i = 0; $i < 5; $i++ ) {
        $query->values([
            'name' => $CAR_NAME[mt_rand(0,12)],
            'power' => mt_rand(300, 1000),
            'year' => mt_rand(2005, 2018),
            'price' => mt_rand(35000, 150000),

        ]);
    }

    $query ->execute();
    drupal_set_message(t('Successfuly add  new 5 cars!'), 'status', FALSE);
}
/*
 * Deleting entities from the table.
 */
function car_module_form_delete_submit($form, &$form_state) {
    $count = db_delete('cars')
        ->execute();
    if ($count) {
        drupal_set_message(t('Successfully  deleted all entities from the table!'),'status', FALSE);
    } else {
        drupal_set_message(t('Table currenly is empty, there is nothing to delete'), 'error', FALSE);
    }
}
/*
 * Button to redirect to car page
 */
function car_module_form_show_submit($form, &$formstate) {
    drupal_goto('cars/table');
}
/*
 * Showing page with tables
 */
function table_show_callback() {

    $query = db_select('cars', 'c');
    $query->fields('c', ['name', 'power', 'year', 'price']);
    $result = $query->execute();

    $rows = [];
    foreach ($result as $row) {
        $rows[] = ['data' => (array) $row];
    }

    // build the table for the nice output.
    $build['table_order'] = [
        '#theme' => 'table',
        '#header' => ['Name', 'Power', 'Year', 'Price'],
        '#rows' => $rows,
    ];

    return $build;
}